schedule: "*/5 * * * *"

logs:
- path: "/tmp/test/logs/delete/*.log"
  type: delete
  condition:
    age: "30m"

- path: "/tmp/test/logs/test.log"
  type: delete
  condition:
    age: "15m"

- path: "/tmp/test/logs/compress"
  type: delete
  condition:
    age: "1h"

# - path: "/tmp/test/logs/delete/*.size.log"
#   type: delete
#   condition:
#     size: "30MB"
  
- path: "/tmp/test/logs/compress/*.log"
  type: rotate
  condition:
    max_keep: 5 // if missing and type rotate it should be default 3
    size: "30MB" // required
    compress: true // if missing and type rotate it should be default true

# - path: "/tmp/test/logs/rotate/*.log"
#   type: compress
#   condition:
#     last_modified: "1h"