schedule: "*/30 * * * *"

logs:
- path: "C:\\workspace\\test\\test_logs\\test1\\*.txt"
  type: rotate
  condition:
    age: "30m"
    max_keep: 5

- path: "C:\\workspace\\test\\test_logs\\test2\\*.txt"
  type: delete
  condition:
    size: "5MB"

- path:
    - "C:\\workspace\\test\\test_logs\\test3\\*.txt"
    - "C:\\workspace\\test\\test_logs\\test4\\*.txt"
  type: delete
  condition:
    age: "30m"